### ISSUE TITLE
Parser does not allow for multiple ISA segments in a single transmission file.

### ISSUE THREAD

**Issue by coolhusker** [imsweb/x12-parser#11]
I have a few customers who have multiple ISA segments in their 837/835s when exporting them out. Initially I thought they were doing something against the spec itself but found that the spec allows. I was able to modify the X12Reader to allow this functionality, but was not sure if it is something you wish to add or not.

http://www.x12.org/rfis/Multiple%20ISA%20and%20IEA%20Segments%20in%20a%20Single%20File.pdf

**Comment by ctmay4** [comment]
Thanks, I'd be very interested in those changes.  

Could you create a pull request?

**Comment by coolhusker** [comment]
Do I need to create a branch first? Sorry, I'm not as versed on github as I
should be.

D

v/r
Dale Alexander
334.462.0297

**Comment by ctmay4** [comment]
Create a fork of the project.  It will be a complete copy of the project under your user name.  Make the proposed changes to your project then open a pull request.  Here are the instructions:

https://help.github.com/articles/creating-a-pull-request/

**Comment by coolhusker** [comment]
Ok...i think i got it..should be visible now
v/r
Dale Alexander
334.462.0297

**Comment by ctmay4** [comment]
Thanks, I see it.  There are merge conflicts though.  Could you please take a look.

@angelaszek could you please review the pull list?

**Comment by coolhusker** [comment]
Done.

D
v/r
Dale Alexander
334.462.0297

**Comment by ctmay4** [comment]
This has been fixed with #12

**Comment by ctmay4** [comment]
FYI the v1.5 of the library was released and is available in Maven Central.
