### ISSUE TITLE
Parser hangs when trying to handle larger files

### ISSUE THREAD

**Issue by menacher** [imsweb/x12-parser#13]
Moderately large files cause the reader to hang. Is there a memory/time efficient way to load files? 
The x12 file below is 22 MB in size and has 25000 claims.
```
X12Reader reader = new X12Reader(X12Reader.FileType.ANSI837_5010_X222, file);
        Loop loop = reader.getLoop();
        Segment segment = loop.getSegment(0);
        System.out.println(segment.toString());
```

**Comment by angelaszek** [comment]
The X12Reader parses the entire file and stores all the claims from the file into memory. Can you try giving more memory to the JVM (-Xmx)?

**Comment by angelaszek** [comment]
We worked on the parser that should be able to process large files more efficiently. We plan to be releasing soon.
