### ISSUE TITLE
no main manifest attribute, in x12-parser-1.6.jar

### ISSUE THREAD

**Issue by arenius** [imsweb/x12-parser#15]
When I try to run the downloaded jar file I receive the following error:

no main manifest attribute, in x12-parser-1.6.jar

This happens on macOS using java 13.0.2 and on Ubuntu linux using openjdk 11.0.5

**Comment by ctmay4** [comment]
This is not a standalone application.  It is a library.  You can use Maven or Gradle to bring it (and its dependencies) into you Java application.
