### ISSUE TITLE
Multiple 2320 loops in 837 (5010) does not parse correctly

### ISSUE THREAD

**Issue by coolhusker** [imsweb/x12-parser#16]
If you have a 837 with multiple 2320 loops under the same 2300 loop, it will capture the first 2320 and then try to make the next SBR segment as a 2000B loop.

**Comment by angelaszek** [comment]
We update the parser a few months which I believe corrected this problem. Can you confirm if you are using the latest version? If you are, can you provide a de-identified sample? Thanks.

**Comment by coolhusker** [comment]
yes to the most recent version,

I have tracked down what is going on...not sure how to fix it just yet...below is a modification to one of the current test messages to show the failure. It has to do with the "last segment" of the loop being the SBR in the institutional 837 vs it not being the last in the professional 837

So the failure is with 837.5010.x223 and . not 837.5010.x222

`ISA*00*          *01*SECRET    *ZZ*SUBMITTERS.ID  *ZZ*RECEIVERS.ID   *030101*1253*U*00501*000000905*1*T*:~
GS*HC*SENDER CODE*RECEIVER CODE*19991231*0802*1*X*005010X223A2~
ST*837*987654*005010X223A2~
BHT*0019*00*0123*19960918*0932*CH~
NM1*41*2*ANGELASZEK MEDICAL*****46*999999999~
PER*IC*DAVID ANGELASZEK*TE*3016809770*EX*123~
NM1*40*2*HEALTH RECEIVER*****46*111222333~
HL*1**20*1~
NM1*85*2*MEDICAL GROUP*****XX*1234567890~
N3*3901 CALVERTON BLVD~
N4*CALVERTON*MD*20705~
REF*EI*123456789~
PER*IC*JANE JONES*TE*3022893453~
PER*IC*JANE JANES*TE*3012833053*EX*201~
NM1*87*2~
N3*227 LASTNER LANE~
N4*GREENBELT*MD*20770~
HL*2*1*22*1~
SBR*P**SUBSCRIBER GROUP******CI~
NM1*IL*1*DOE*JOHN*T**JR*MI*123456~
NM1*PR*2*HEALTH INSURANCE COMPANY*****PI*11122333~
CLM*A37YH556*500***11:B:1*Y*A*Y*I*P~
HI*BK*8901*BF*87200*BF:5559~
SBR*S*01*******CI~
OI***Y***Y~
NM1*IL*1*DOE*JOHN*D***MI*ABCDER1234~
NM1*PR*2*AETNA*****PI*54321~
N3*A PO BOX~
N4*ANYTOWN*AL*32143~
SBR*T*18*******CI~
OI***Y***Y~
NM1*IL*1*DOE*JANE****MI*GDAFA1232~
N3*A STREET ADDRESS~
N4*A TOWN*AL*54321~
NM1*PR*2*ANOTHER NAME*****PI*12345~
N3*PO BOX 1234~
N4*FRED*AL*12345~
LX*1~
SV1*HC:99211:25*12.25*UN*1*11**1**Y~
DTP*472*RD8*20050314-20050325~
HL*2*3*22*1~
SBR*P**SUBSCRIBER GROUP TWO******CI~
NM1*IL*1*DOE*DAVID*J**JR*MI*123456~
NM1*PR*2*HEALTH INSURANCE COMPANY TWO*****PI*11122333~
CLM*A37YH667*500***11:B:1*Y*A*Y*I*P~
HI*BK*1987*BF*4134*BF:5559~
LX*2~
SV1*HC:478331:25*12.25*UN*1*11**1:2:3**Y~
DTP*472*RD8*20050322-20050325~
SE*25*987654~
GE*1*1~
IEA*1*000000905~
`

**Comment by angelaszek** [comment]
Thanks. That helped narrow things down and it also explains why I didn't see it when testing with X222. I will be updating with a fix soon.
