### ISSUE TITLE
Need a way to deserialize, modify then re-serialize X12 document

### ISSUE THREAD

**Issue by nddipiazza** [imsweb/x12-parser#21]
I would like to parse an x12 file, then make some some changes via the java pojo, then save it back to x12. 

Is this supported already? or do I need to make a PR?

**Comment by ctmay4** [comment]
Unfortunately this is not supported at this time.  It is something we hope to have at some point in the future.  If you would like to contribute a pull request that would be great.

**Comment by nddipiazza** [comment]
@ctmay4 i went ahead and created a PR. it was pretty simple, you had a lot of the code already there, it was just a matter of getting it to be in the correct order.

**Comment by ctmay4** [comment]
Thanks.  We will take a look.
