### ISSUE TITLE
Need methods to convert back and forth between X12 <-> JSON, and X12 <-> XML

### ISSUE THREAD

**Issue by nddipiazza** [imsweb/x12-parser#23]
We currently have methods to get XML and JSON representation of the x12 documents.

I need methods to get the XML and JSON back to X12 again. 

Here we created the ability to write the Pojo to X12: https://github.com/imsweb/x12-parser/pull/22 , so what we have left to do is load the XML/JSON to Pojo.

**Comment by angelaszek** [comment]
Thanks for your work on the other issue. Did you want to do the pull request for this as well?

**Comment by nddipiazza** [comment]
Hi @angelaszek you're welcome. 

I took a quick stab at this issue and I'm not familiar with XStream so I might need a little guidance like you did on the last PR.

So here is what i've got so far:

https://github.com/imsweb/x12-parser/pull/24/files

Can you take a look and see if my "strategy" here is anywhere close to something that would work? I get the feeling that I'll have to do a lot of special magic here to make this work.

**Comment by angelaszek** [comment]
@nddipiazza sorry - I have been caught up with a few other things. Just wanted you to know I saw this and will be getting to it soon.

**Comment by nddipiazza** [comment]
@angelaszek no problem at all! thanks for your time.

**Comment by angelaszek** [comment]
I do have a little experience using XStream but I am not expert either. It looks like you're going in the right direction as your start.

**Comment by nddipiazza** [comment]
@angelaszek i'm closing this, as I do not think it is useful. this pr https://github.com/imsweb/x12-parser/pull/26 does what i need by converting x12 into html form.
