### ISSUE TITLE
Question - rendering human-readable X12 HTML from XML?

### ISSUE THREAD

**Issue by nddipiazza** [imsweb/x12-parser#25]
I notice we have some XML files in this project that could possibly provide a lookup to create a human readable X12 rendering. These files: https://github.com/imsweb/x12-parser/tree/master/src/main/resources/mapping

They are not XSD, but instead an XML format that describes the schema of the x12 docs.

Has anyone been able to use these or something related to take the X12 XML output and render a human readable HTML form with the data? 

While the `theJson`/`toXml` functions available make much more readable output than x12 itself, it's still gibberish to most common folk. I'd be interested in an XSLT or something. 

Have ya'll done anything like this? Hoping not to re-invent the wheel here.

**Comment by angelaszek** [comment]
No we haven't implemented something like this yet.

**Comment by nddipiazza** [comment]
@angelaszek  I created a pr for it. https://github.com/imsweb/x12-parser/pull/26
