### ISSUE TITLE
Need a "detectType" method 

### ISSUE THREAD

**Issue by nddipiazza** [imsweb/x12-parser#27]
I often get an x12 text string, and need to know what format it is.

We should create a `detectType` method.

**Comment by angelaszek** [comment]
Just to confirm - the field you want to check for this is GS08?

**Comment by nddipiazza** [comment]
yes. right now the work around is to just loop through all the types until you find one that doesn't bomb. not efficient.

**Comment by angelaszek** [comment]
I believe the first two segments (ISA and GS) in the x12's are pretty consistent across versions. At least I have seen that in the versions I am familiar with. The ISA segment has a fixed length and defines the separators in specific positions in that segment. I think we can use that to determine the value of GS08.

**Comment by nddipiazza** [comment]
i thought i would need this, but in practice i'm finding i don't need this, because each source system is labelling what type of x12 file it is.

**Comment by angelaszek** [comment]
Are we OK to close this then? I don't need this functionality right now. If this is needed later we can create a new issue for it then.
