### ISSUE TITLE
Support for 005010X231A1 - 999 Implementation Acknowledgment

### ISSUE THREAD

**Issue by nddipiazza** [imsweb/x12-parser#28]
need support for x12 files of format 005010X231A1

see http://anyflip.com/fveo/asmd/basic

**Comment by angelaszek** [comment]
I think the first step is putting the specs into an XML like the other supported formats use. I would need to check if there is an open source one readily available somewhere online. The specs don't seem too complicated though if there isn't one.

**Comment by nddipiazza** [comment]
Hey @angelaszek  i took a look into the project and see this https://github.com/imsweb/x12-parser/blob/master/src/main/resources/mapping/999.5010.xml

looks pretty promising. I tried plugging it in, but got all sorts of errors when I tried parsing 999's with it.

**Comment by angelaszek** [comment]
Do you have any 999 sample files? I can take a look using them.

**Comment by nddipiazza** [comment]
@angelaszek  some examples here:

https://healthcare.pilotfishtechnology.com/edi-999-format-example/
http://www.novitas-solutions.com/webcenter/content/conn/UCM_Repository/uuid/dDocName:00004759
https://ediacademy.com/blog/999-acknowledgement-hipaa-edi/

I looked them up versus what I have in my system and they seem to be accurate examples. I can't send any that are actually in use in my system because I only have prod examples.

**Comment by nddipiazza** [comment]
@angelaszek created a PR to add this support. added a unit test for 999 and 277ca both accept and reject.

**Comment by nddipiazza** [comment]
i found a gold mine of useful 5010 examples https://www.emedny.org/HIPAA/5010/5010_sample_files/

**Comment by nddipiazza** [comment]
Fixed.
