### ISSUE TITLE
Examples for converting x12  837 and 835 to xml using java using this parser

### ISSUE THREAD

**Issue by aws-csap** [imsweb/x12-parser#41]
I am looking for examples on how to convert x12 837 and 835 files to xml in java using this parser?

**Comment by angelaszek** [comment]
Here is an example of reading an ANSI 837 5010 X222 file and printing the results out as xml. 

For an 835 file you would just need to change the FileType.ANSI837_5010_X222 to the appropriate type. 

```
URL url = this.getClass().getResource("/837_5010/x12_complex.txt");
        X12Reader reader = new X12Reader(FileType.ANSI837_5010_X222, new File(url.getFile()));
        List<Loop> loops = reader.getLoops();
        
        for (Loop loop : loops)
            System.out.println(loop.toXML());
```

**Comment by nddipiazza** [comment]
just an fyi. it will not export to common microsoft x12 schema and we cannot add that either because the dtd/xsd license is not open source.

**Comment by nddipiazza** [comment]
@BruceEdu can we close this issue?

**Comment by nddipiazza** [comment]
@angelaszek we should close this issue. we answered his question.
