### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by Edwardiv1** [imsweb/x12-parser#6]
Hi, is there any example code for creating X12 837 5010 data (or anything else really that shows how to use the library)?

Thanks

**Comment by angelaszek** [comment]
Here is a sample file with some example code about how one could use the library to read it. I hope this helps. 
[sample-claim-github.txt](https://github.com/imsweb/x12-parser/files/2082909/sample-claim-github.txt)
[sample-code-github.txt](https://github.com/imsweb/x12-parser/files/2082910/sample-code-github.txt)

**Comment by AswiniBhuvanesh** [comment]
Hi
Is there any sample to refer for EDI Writer

**Comment by angelaszek** [comment]
We don't have any samples that refer to EDI writer. We just have samples of how this library can be used to process X12 files.
