### ISSUE TITLE
README.md is pretty incomplete.

### ISSUE THREAD

**Issue by ModemMisuser** [imsweb/x12-parser#62]
In README.md, in the "Creating and Writing an X12 File" section there are numerous lines of the form "addElement(segment, "01", "00");" ... There is no such method (and the object upon which the method is supposed to exist is left off) - may want to fix this, as users of this library will find themselves stuck (as I am).

**Comment by ctmay4** [comment]
Sorry about that.  Looks like the code was refactored and the README didn't get updated.  It currently says:

```java
Segment segment = new Segment("ISA");
addElement(segment, "01", "00");
```

and should be 

```java
Segment segment = new Segment("ISA");
segment.addElement("01", "00");
```

I'll update the README.

**Comment by ModemMisuser** [comment]
> Sorry about that. Looks like the code was refactored and the README didn't get updated. It currently says:
> 
> ```java
> Segment segment = new Segment("ISA");
> addElement(segment, "01", "00");
> ```
> 
> and should be
> 
> ```java
> Segment segment = new Segment("ISA");
> segment.addElement("01", "00");
> ```
> 
> I'll update the README.

Excellent - I was in the process of creating a helper method in the class I'm using to play with the library, but I'll convert to segement.addElement instead.

**Comment by ctmay4** [comment]
I just updated the README.

**Comment by ModemMisuser** [comment]
Actually, there is no addElement method on Segment that takes 2 Strings as arguments. :D

**Comment by ctmay4** [comment]
Ugh.  You are correct.  You need to pass an `Element`, which does have a 2 string constructor.  I will fix the README.

**Comment by ctmay4** [comment]
By the way, you can look at the file SegmentTest.java to see examples.

**Comment by ctmay4** [comment]
I updated the README and added a helper method to `Segment` that takes two strings.  However I am not ready to do a release.  So for now you will need to do the `new Element` constructor.
