### ISSUE TITLE
Documentation error?

### ISSUE THREAD

**Issue by Edwardiv1** [imsweb/x12-parser#70]
The documentation has the following example:
```
Loop isaLoop = new Loop("ISA_LOOP");

Segment segment = new Segment("ISA");
segment.addElement("01", "00");
segment.addElement("02", "          ");
segment.addElement("03", "01");
```

but running that results in:
`The method addElement(int, Element) in the type Segment is not applicable for the arguments (String, String)`

Has the library changed since that documentation was written?

**Comment by angelaszek** [comment]
It looks like this was closed. I just wanted to comment that I do see Segment.addElement(String, String) as supported in the library.
